name: Generate Task

on:
  workflow_dispatch:
    inputs:
      theme:
        description: 'Theme for the new task'
        required: true
        default: 'Implement a simple text-based adventure game.'
      difficulty:
        description: 'Difficulty level for the new task'
        required: true
        type: choice
        options:
          - easy
          - medium
          - hard
        default: medium
      language:
        description: 'Natural language for the task description'
        required: true
        default: 'English'

permissions:
  contents: write  
  pull-requests: write

jobs:
  generate-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai

      - name: Generate new_task.md
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_TOKEN }}
          THEME: ${{ github.event.inputs.theme }}
          DIFFICULTY: ${{ github.event.inputs.difficulty }}
          LANGUAGE: ${{ github.event.inputs.language }}
        run: |
          python scripts/generate_new_task.py "${{ secrets.OPENAI_TOKEN }}"

      - name: Commit and Push changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add tasks/new_task.md
          git commit -m "Generate new_task.md based on the provided theme"
          git push
